version: '3'
services:
  local-mysql:
    container_name: local-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: sagenappcore
      MYSQL_ROOT_PASSWORD: sagenappcore123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  registration-login:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8099:8080
    command: mvn clean spring-boot:run
    depends_on:
      - local-mysql
